server:
  port: 8003

redis:
  host: localhost
  port: 6379

spring:
  datasource:
    url: jdbc:mysql://localhost:3300/sale_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop   # update | validate | create | create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jwt:
    signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
    access-token-expiration: 21600000    # 2 tiếng (2 * 60 * 60 * 1000 ms)
    refresh-token-expiration: 604800000 # 7 ngày (7 * 24 * 60 * 60 * 1000 ms)
    short-lived-token: 3600000

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

outbound:
  identity:
    client-id: 123
    client-secret: 123456
    redirect-uri: localhost:3302

# logging
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
