server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course_service
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1942004anh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  jwt:
    signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
    access-token-expiration: 21600000    # 2 tiếng (2 * 60 * 60 * 1000 ms)
    valid-duration: 21600000
    refresh-token-expiration: 604800000 # 7 ngày (7 * 24 * 60 * 60 * 1000 ms)
    refreshable-duration: 604800000
    short-lived-token: 3600000
