server:
  port: 8081
  servlet:
    context-path: /course

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/course_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 1942004anh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
