server:
  port: 8081

aws:
  accessKeyId: AKIAWDVGBIV2PUTG6MHM
  secretAccessKey: +S41d/55eDu/UIHQuMYoLitHcCn/GR5/FMjAWerS
  bucketName: sample-s3-ntd
  key-store: https://sample-s3-ntd.s3.ap-southeast-1.amazonaws.com
  region: ap-southeast-1


cloudinary:
  cloud_name: df3snzgv2
  api_key: 242516133233971
  api_secret: 8kYfliJa45faDUqNJdH6-9HimZk

spring:
  datasource:
    url: jdbc:mysql://localhost:3300/course_service
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  jwt:
    signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
    access-token-expiration: 21600000    # 2 tiếng (2 * 60 * 60 * 1000 ms)
    valid-duration: 21600000
    refresh-token-expiration: 604800000 # 7 ngày (7 * 24 * 60 * 60 * 1000 ms)
    refreshable-duration: 604800000
    short-lived-token: 3600000

grpc:
  server:
    port: 9091

  client:
    user-service:
      address: static://localhost:9090
      negotiation-type: plaintext